### PR TITLE
Add torch weight conversion

### PR DESCRIPTION
**Pull request by DongyaoZhu**

### CODE REVIEW

**Comment by SamitHuang** [comment]
Why do we need numpy as the intermediate format?

**Comment by DongyaoZhu** [comment]
> intermediate

I'm not sure if you can import mindspore and torch at the same time

**Comment by wtomin** [comment]
I think the current .py files are not straightforward enough to use. My suggestion is to use just two .py files:
- pt2ms.py: accepting `version` (1 or 2) and `pt_weight_path` as arguments;
- ms2pt.py: accepting `version` (1 or 2) and `ms_weight_path` as arguments.

`.pkl` files may be saved as intermediate states, or deleted after weights translation.

**Comment by DongyaoZhu** [comment]
done

> I think the current .py files are not straightforward enough to use. My suggestion is to use just two .py files:
> 
> - pt2ms.py: accepting `version` (1 or 2) and `pt_weight_path` as arguments;
> 
> - ms2pt.py: accepting `version` (1 or 2) and `ms_weight_path` as arguments.
> 
> 
> 
> `.pkl` files may be saved as intermediate states, or deleted after weights translation.

**Comment by vigo999** [comment]
please move tools/* to https://github.com/mindspore-lab/mindone/tree/master/examples/stable_diffusion_v2/tools/*
conversion is only for stable diffusion models. 
examples/stable_diffusion_v2/tools/
 - pt2ms.py
 - xxxx.py
mv readme.md examples/stable_diffusion_v2/pt2ms.md

**Comment by DongyaoZhu** [comment]
> please move tools/* to https://github.com/mindspore-lab/mindone/tree/master/examples/stable_diffusion_v2/tools/* conversion is only for stable diffusion models. examples/stable_diffusion_v2/tools/
> 
> * pt2ms.py
> * xxxx.py
>   mv readme.md examples/stable_diffusion_v2/pt2ms.md

done

**Review by congw729 — APPROVED** [review]
LGTM

**Review by vigo999 — APPROVED** [review]

**Pull request merged**
