### PR TITLE
delete unused layers; fix negprompt file len mismatch

### PR DESCRIPTION
**Pull request by DongyaoZhu**

### CODE REVIEW

**Review by congw729 — APPROVED** [review]
LGTM

**Comment by vigo999** [comment]
@SamitHuang please  check this fix

**Comment by SamitHuang** [comment]
Due to negative prompt length bug fixed in https://github.com/mindspore-lab/mindone/pull/48, via padding
``` python
        blank_negative_prompt = batch_size * [""]
        for _ in range(len(data) - len(negative_data)):
        negative_data.append(blank_negative_prompt)
```

I remove conflicting code in this pr.

**Comment by DongyaoZhu** [comment]
> 

ok

**Pull request merged**
