### PR TITLE
fixed test bug for import path

### PR DESCRIPTION
**Pull request by Songyuanwei**

### CODE REVIEW

**Comment by zhtmike** [comment]
what bug it already has?

**Comment by Songyuanwei** [comment]
> what bug it has originally?

https://e.gitee.com/mind_spore/issues/list?issue_type_category=bug&issue=I9034O
Traceback (most recent call last):
  File "tests/st/test_overfit.py", line 17, in <module>
    from _common import down_checkpoint
  File "/data/TDT_deployment/solution_test/cases/02network/11one/sd15/train/test_ms_sd15_dreambooth_overfit_train_ascend_1p_0002/examples/stable_diffusion_v2/tests/st/_common.py", line 8, in <module>
    from tools.eval.fid.utils import Download
ModuleNotFoundError: No module named 'tools.eval'

**Comment by zhtmike** [comment]
why this fix can resolve the bug? don't understand..

**Comment by Songyuanwei** [comment]
> > what bug it has originally?
> 
> https://e.gitee.com/mind_spore/issues/list?issue_type_category=bug&issue=I9034O Traceback (most recent call last): File "tests/st/test_overfit.py", line 17, in from _common import down_checkpoint File "/data/TDT_deployment/solution_test/cases/02network/11one/sd15/train/test_ms_sd15_dreambooth_overfit_train_ascend_1p_0002/examples/stable_diffusion_v2/tests/st/_common.py", line 8, in from tools.eval.fid.utils import Download ModuleNotFoundError: No module named 'tools.eval'

it is need add __init__.py to tools and use 

> > what bug it has originally?
> 
> https://e.gitee.com/mind_spore/issues/list?issue_type_category=bug&issue=I9034O Traceback (most recent call last): File "tests/st/test_overfit.py", line 17, in from _common import down_checkpoint File "/data/TDT_deployment/solution_test/cases/02network/11one/sd15/train/test_ms_sd15_dreambooth_overfit_train_ascend_1p_0002/examples/stable_diffusion_v2/tests/st/_common.py", line 8, in from tools.eval.fid.utils import Download ModuleNotFoundError: No module named 'tools.eval'

it is need add __init__.py to tools and use sys.path.insert(0, ".") instead of sys.path.append(".") for _common.py

**Comment by Songyuanwei** [comment]
> why this fix can resolve the bug? don't understand..

Running locally does not require modification, but the test team will automatically set `export PYTHONPATH=solution_test_path:$PYTHONPATH` the monitoring case to run on their own CI, and this modification is necessary. This modification will not affect local Run

**Review by zhtmike — APPROVED** [review]

**Pull request merged**
